# -*- coding: utf-8 -*-
"""
Created on Tue Aug 25 14:06:09 2020

@author: u6265553
"""

'''This script generates the inverse transformation function required 
for moving lens shift-scale calibration to align the synthetic images 
generated by Blender to a reference image to obtain fully in-focus image 
applying image stacking. This script calculates the shift and scaling 
required to align the images and generate required transformaton functions.'''

import glob
import numpy as np
import cv2
from skimage import restoration
from scipy.signal import convolve2d as conv2
from scipy import misc, optimize, special
from matplotlib import pylab as plt


pixelsize=4e-6
#focal length of the lens in meter
f_lens=65e-3
#focal length of the lens in pixel
f_lens_pixel=f_lens/pixelsize

forward_translation=-0.021
backward_translation=0.019
average_camera_distance=0.15

max_camera_distnace=average_camera_distance+backward_translation
f_camera=average_camera_distance*f_lens/(average_camera_distance-f_lens)
#focal length of the camera in pixel
f_camera_pixel=f_camera/pixelsize
num_of_img=64
#linear displacement of the camera
del_d=(backward_translation-forward_translation)/num_of_img #in meter
del_d_pixel=del_d/pixelsize #in pixel
d_pixel=max_camera_distnace/pixelsize

d_list=np.zeros([num_of_img])

for i in range(num_of_img):
          
    d_list[i]=d_pixel-i*del_d_pixel

d_ref_pixel=d_list[63]

scaling=np.zeros([num_of_img])
shift_x=np.zeros([num_of_img])
shift_y=np.zeros([num_of_img])
H=np.zeros([num_of_img,3,3])

for i in range(num_of_img):
           
    #depth of the target calibration target
    d_target_pixel=d_list[i]
    
    scaling[i]=d_ref_pixel/d_target_pixel          
    shift_x[i]=(1-scaling[i])*(1080/2)
    shift_y[i]=(1-scaling[i])*(720/2)
    
    h=np.array([[scaling[i],0,shift_x[i]],[0,scaling[i],shift_y[i]],[0,0,1]])
    H[i]=(np.linalg.inv(h))

H_file = 'F:/Arif/moving_lens/blender_images/Hs.npz'
homographies = []
np.savez(H_file, homographies=H)
   